# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/wearher_service

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run flake8
          command: |
            . venv/bin/activate
            flake8 weather_service

      - run:
          name: run integration test
          command: |
            . venv/bin/activate
            python manage.py makemigrations
            python manage.py migrate
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports

  deploy:
    docker:
      - image: test:latest
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git poc_telegram_bot
          environment:
            HEROKU_API_KEY: 21f97f96-e01c-4b52-be8d-661946064e16
            HEROKU_APP_NAME: weather1-test

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: poc_telegram_bot
