# Generated by Django 2.1.7 on 2019-03-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.TextField(max_length=100)),
                ('cord_lon', models.TextField()),
                ('cord_lat', models.TextField()),
                ('weather_main', models.TextField()),
                ('weather_description', models.TextField()),
                ('temp', models.TextField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
