# Generated by Django 2.1.7 on 2019-03-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20190321_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='cord_lat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weather',
            name='cord_lon',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temp',
            field=models.CharField(max_length=100),
        ),
    ]
